version: '3.0'
volumes:
  rabbitmq-data:

services:
        schedule:
                 build: ./schedule/
                 restart: on-failure
        publisher:
                 build: ./publisher/
                 restart: on-failure

        rabbitmq:
                image: rabbitmq:3-management
                volumes:
                        - rabbitmq-data:/var/lib/rabbitmq
                restart: on-failure
                ports:
                        - 15672:15672
                        - 5672:5672
                environment:
                        - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.9


