version: '3.0'
volumes:
  pgsql-data:

services:
        schedule:
                 build: ./schedule/
                 env_file: docker-compose.envs
                 restart: on-failure
        publisher:
                 build: ./publisher/
                 env_file: docker-compose.envs
                 restart: on-failure
        api:
                 build: ./api/
                 env_file: docker-compose.envs
                 restart: on-failure
                 ports:
                       - 8280:8280
        ui:
                 build: ./ui/
                 env_file: docker-compose.envs
                 restart: on-failure
                 ports:
                       - 8180:8180
        pgsql:
                image: postgres
                restart: always
                environment:
                        - POSTGRES_PASSWORD=Pasd@1234
                volumes:
                        - pgsql-data:/var/lib/rabbitmq
                restart: on-failure
                ports:
                        - 5432:5432
        adminer:
                image: adminer
                restart: always
                ports:
                       - 8080:8080
