version: '3.0'
volumes:
  pgsql-data:

services:
        schedule:
                 build: ./schedule/
                 restart: on-failure
        publisher:
                 build: ./publisher/
                 restart: on-failure
        api:
                 build: ./api/
                 restart: on-failure

        pgsql:
                image: postgres
                restart: always
                environment:
                        - POSTGRES_PASSWORD=Pasd@1234
                volumes:
                        - pgsql-data:/var/lib/rabbitmq
                restart: on-failure
                ports:
                        - 5432:5432
        adminer:
                image: adminer
                restart: always
                ports:
                        - 8080:8080


